version: '3'
services:
  flight-prices-api:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - flight-prices-net
networks:
  flight-prices-net:
