FROM golang:1.23-alpine

ENV APP_HOME /go/src/github.com/syned13/flight-prices-api

RUN mkdir -p $APP_HOME
ADD . $APP_HOME
WORKDIR $APP_HOME
RUN mkdir -p build

RUN go get github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -build="go build -o ./build/app ./cmd/main.go " -command="./build/app"