services:
  amadeus-mock:
    image: mockserver/mockserver:latest
    ports:
      - 8085:80
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/amadeus.json
      MOCKSERVER_SERVER_PORT: 80
      MOCKSERVER_DISABLE_SYSTEM_OUT: "true"
      DOCKER_DEFAULT_PLATFORM: linux/amd64
    volumes:
      - type: bind
        source: ./mocks/mockserver/amadeus.json
        target: /config/amadeus.json
    networks:
      - flight-prices-net
  serpapi-mock:
    image: mockserver/mockserver:latest
    ports:
      - 8086:80
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/serpapi.json
      MOCKSERVER_SERVER_PORT: 80
      MOCKSERVER_DISABLE_SYSTEM_OUT: "true"
      DOCKER_DEFAULT_PLATFORM: linux/amd64
    volumes:
      - type: bind
        source: ./mocks/mockserver/serpapi.json
        target: /config/serpapi.json
    networks:
      - flight-prices-net
  flightapi-mock:
    image: mockserver/mockserver:latest
    ports:
      - 8087:80
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/flightapi.json
      MOCKSERVER_SERVER_PORT: 80
      MOCKSERVER_DISABLE_SYSTEM_OUT: "true"
      DOCKER_DEFAULT_PLATFORM: linux/amd64
    volumes:
      - type: bind
        source: ./mocks/mockserver/flightapi.json
        target: /config/flightapi.json
    networks:
      - flight-prices-net
networks:
  flight-prices-net: