version: '3'
services:
  flight-prices-api:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - flight-prices-net
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: flightprices
      MONGO_INITDB_ROOT_PASSWORD: flightprices123
    networks:
      - flight-prices-net
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - flight-prices-net
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: flightredis123
    command: ["redis-server", "--requirepass", "flightredis123"]
networks:
  flight-prices-net:
volumes:
  mongodb_data:
  redis_data:
